{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "oauth2-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "oauth2-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: oauth2-proxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - --provider=oidc
            - --oidc-issuer-url={{ required "oauth2-proxy.jwt.issuer is required" .Values.jwt.issuer }}
            - --client-id={{ required "oauth2-proxy.clientId is required" .Values.clientId }}
            - --redirect-url={{ include "oauth2-proxy.redirectUrl" . }}
            - --cookie-domain={{ include "oauth2-proxy.cookieDomain" . }}
            - --email-domain={{ index .Values.emailDomains 0 }}
            - --upstream=static://202
            - --reverse-proxy=true
            - --http-address=0.0.0.0:{{ .Values.service.port }}
            {{- if .Values.jwt.audience }}
            - --oidc-audience-claim=aud
            {{- end }}
            {{- if .Values.skipJwtBearerTokens }}
            - --skip-jwt-bearer-tokens=true
            {{- if and .Values.jwt.issuer .Values.jwt.audience }}
            - --extra-jwt-issuers={{ .Values.jwt.issuer }}={{ .Values.jwt.audience }}
            {{- end }}
            {{- end }}
          env:
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ required "oauth2-proxy.existingSecret is required" .Values.existingSecret }}
                  key: {{ .Values.secretKeys.clientSecret }}
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: {{ .Values.secretKeys.cookieSecret }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
